//! Incremental Tree-sitter syntax boundary for CR source files.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use thiserror::Error;
use tree_sitter::{InputEdit, Language, LanguageError, Parser, Point, Range, Tree};
use tree_sitter_language::LanguageFn;

unsafe extern "C" {
    fn tree_sitter_cr() -> *const ();
}

/// Tree-sitter language function generated from `grammar/grammar.js`.
pub const LANGUAGE: LanguageFn = unsafe {
    // SAFETY: `tree_sitter_cr` is generated by the pinned Tree-sitter CLI and
    // linked from `grammar/src/parser.c` by `build.rs`.
    LanguageFn::from_raw(tree_sitter_cr)
};

/// A zero-based source location using Tree-sitter's byte-column convention.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SourcePoint {
    pub row: usize,
    pub column: usize,
}

impl From<Point> for SourcePoint {
    fn from(point: Point) -> Self {
        Self {
            row: point.row,
            column: point.column,
        }
    }
}

/// A source-backed byte range and its human-readable endpoints.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceSpan {
    pub path: PathBuf,
    pub start_byte: usize,
    pub end_byte: usize,
    pub start: SourcePoint,
    pub end: SourcePoint,
}

/// Severity of a structured compiler diagnostic.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DiagnosticSeverity {
    Error,
    Warning,
    Note,
}

/// A secondary source location attached to a diagnostic.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RelatedDiagnostic {
    pub message: String,
    pub span: SourceSpan,
}

/// A stable, source-based diagnostic emitted by the syntax boundary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Diagnostic {
    pub code: &'static str,
    pub severity: DiagnosticSeverity,
    pub message: String,
    pub primary_span: SourceSpan,
    pub related: Vec<RelatedDiagnostic>,
}

/// A parsed translation unit and the exact source that produced it.
#[derive(Clone)]
pub struct SyntaxUnit {
    path: PathBuf,
    source: Arc<str>,
    tree: Tree,
    diagnostics: Vec<Diagnostic>,
}

impl SyntaxUnit {
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    #[must_use]
    pub fn source(&self) -> &str {
        &self.source
    }

    #[must_use]
    pub fn tree(&self) -> &Tree {
        &self.tree
    }

    #[must_use]
    pub fn text(&self, node: tree_sitter::Node<'_>) -> &str {
        &self.source[node.byte_range()]
    }

    #[must_use]
    pub fn span(&self, node: tree_sitter::Node<'_>) -> SourceSpan {
        node_span(&self.path, node)
    }

    #[must_use]
    pub fn diagnostics(&self) -> &[Diagnostic] {
        &self.diagnostics
    }

    #[must_use]
    pub fn has_errors(&self) -> bool {
        self.diagnostics
            .iter()
            .any(|diagnostic| diagnostic.severity == DiagnosticSeverity::Error)
    }
}

/// A parsed unit plus the ranges whose syntax changed after an edit.
pub struct ReparseResult {
    pub unit: SyntaxUnit,
    pub changed_ranges: Vec<Range>,
}

/// Fatal failures that prevent Tree-sitter from producing a syntax tree.
#[derive(Debug, Error)]
pub enum SyntaxFatalError {
    #[error("failed to load the generated CR grammar: {0}")]
    Language(#[from] LanguageError),
    #[error("Tree-sitter canceled parsing before producing a syntax tree")]
    ParseCanceled,
}

/// Stateful CR parser that can reuse an edited Tree-sitter tree.
pub struct SyntaxParser {
    parser: Parser,
}

impl SyntaxParser {
    pub fn new() -> Result<Self, SyntaxFatalError> {
        let mut parser = Parser::new();
        parser.set_language(&language())?;
        Ok(Self { parser })
    }

    pub fn parse(
        &mut self,
        path: PathBuf,
        source: impl Into<Arc<str>>,
    ) -> Result<SyntaxUnit, SyntaxFatalError> {
        let source = source.into();
        let tree = self
            .parser
            .parse(source.as_bytes(), None)
            .ok_or(SyntaxFatalError::ParseCanceled)?;
        Ok(build_unit(path, source, tree))
    }

    pub fn reparse(
        &mut self,
        previous: &SyntaxUnit,
        source: impl Into<Arc<str>>,
    ) -> Result<ReparseResult, SyntaxFatalError> {
        let source = source.into();
        if previous.source.as_ref() == source.as_ref() {
            return Ok(ReparseResult {
                unit: previous.clone(),
                changed_ranges: Vec::new(),
            });
        }

        let edit = single_input_edit(&previous.source, &source);
        let mut edited_tree = previous.tree.clone();
        edited_tree.edit(&edit);
        let tree = self
            .parser
            .parse(source.as_bytes(), Some(&edited_tree))
            .ok_or(SyntaxFatalError::ParseCanceled)?;
        let changed_ranges = edited_tree.changed_ranges(&tree).collect();

        Ok(ReparseResult {
            unit: build_unit(previous.path.clone(), source, tree),
            changed_ranges,
        })
    }
}

impl Default for SyntaxParser {
    fn default() -> Self {
        Self::new().expect("the generated CR grammar must match tree-sitter")
    }
}

#[must_use]
pub fn language() -> Language {
    LANGUAGE.into()
}

fn build_unit(path: PathBuf, source: Arc<str>, tree: Tree) -> SyntaxUnit {
    let diagnostics = collect_parse_diagnostics(&path, &tree);
    SyntaxUnit {
        path,
        source,
        tree,
        diagnostics,
    }
}

fn collect_parse_diagnostics(path: &Path, tree: &Tree) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();
    let mut cursor = tree.walk();

    loop {
        let node = cursor.node();
        if node.is_error() || node.is_missing() {
            let (code, message) = if node.is_missing() {
                (
                    "CRS0002",
                    format!("expected `{}` before this location", node.kind()),
                )
            } else {
                ("CRS0001", "unable to parse this syntax".to_owned())
            };
            diagnostics.push(Diagnostic {
                code,
                severity: DiagnosticSeverity::Error,
                message,
                primary_span: node_span(path, node),
                related: Vec::new(),
            });
        }

        if cursor.goto_first_child() {
            continue;
        }

        while !cursor.goto_next_sibling() {
            if !cursor.goto_parent() {
                return diagnostics;
            }
        }
    }
}

fn node_span(path: &Path, node: tree_sitter::Node<'_>) -> SourceSpan {
    SourceSpan {
        path: path.to_path_buf(),
        start_byte: node.start_byte(),
        end_byte: node.end_byte(),
        start: node.start_position().into(),
        end: node.end_position().into(),
    }
}

fn single_input_edit(old: &str, new: &str) -> InputEdit {
    let old_bytes = old.as_bytes();
    let new_bytes = new.as_bytes();
    let mut start = old_bytes
        .iter()
        .zip(new_bytes)
        .take_while(|(left, right)| left == right)
        .count();
    while !old.is_char_boundary(start) || !new.is_char_boundary(start) {
        start -= 1;
    }

    let max_suffix = old_bytes.len().min(new_bytes.len()) - start;
    let mut suffix = old_bytes
        .iter()
        .rev()
        .zip(new_bytes.iter().rev())
        .take(max_suffix)
        .take_while(|(left, right)| left == right)
        .count();
    while !old.is_char_boundary(old_bytes.len() - suffix)
        || !new.is_char_boundary(new_bytes.len() - suffix)
    {
        suffix -= 1;
    }

    let old_end = old_bytes.len() - suffix;
    let new_end = new_bytes.len() - suffix;
    InputEdit {
        start_byte: start,
        old_end_byte: old_end,
        new_end_byte: new_end,
        start_position: point_at(old, start),
        old_end_position: point_at(old, old_end),
        new_end_position: point_at(new, new_end),
    }
}

fn point_at(source: &str, byte: usize) -> Point {
    let prefix = &source.as_bytes()[..byte];
    let row = prefix.iter().filter(|byte| **byte == b'\n').count();
    let column = prefix
        .iter()
        .rposition(|byte| *byte == b'\n')
        .map_or(prefix.len(), |newline| prefix.len() - newline - 1);
    Point::new(row, column)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_cr_extensions_as_named_nodes() {
        let source = r#"
__async int fetch(int socket) {
    int bytes = __await read_socket(socket);
    int alias = __awite read_socket(socket);
    __yield bytes + alias;
    __defer close_socket(socket);
    return bytes;
}
"#;
        let mut parser = SyntaxParser::new().expect("grammar loads");
        let unit = parser
            .parse(PathBuf::from("fetch.cr"), source)
            .expect("source parses");

        assert!(!unit.has_errors(), "diagnostics: {:?}", unit.diagnostics());
        let sexp = unit.tree().root_node().to_sexp();
        for kind in [
            "async_specifier",
            "await_expression",
            "yield_expression",
            "defer_statement",
        ] {
            assert!(sexp.contains(kind), "missing {kind} in {sexp}");
        }
    }

    #[test]
    fn reports_incomplete_edits_without_failing_to_parse() {
        let source = "__async int pending(void) { return __await\n}";
        let mut parser = SyntaxParser::new().expect("grammar loads");
        let unit = parser
            .parse(PathBuf::from("pending.cr"), source)
            .expect("Tree-sitter returns a recovery tree");

        assert!(unit.has_errors());
        assert!(
            unit.diagnostics()
                .iter()
                .any(|diagnostic| diagnostic.code == "CRS0001")
        );
    }

    #[test]
    fn incremental_reparse_reports_changed_ranges() {
        let old_source = "int value(void) { return 1; }\n";
        let new_source = "int value(void) { return __await task; }\n";
        let mut parser = SyntaxParser::new().expect("grammar loads");
        let old = parser
            .parse(PathBuf::from("value.cr"), old_source)
            .expect("old source parses");
        let reparsed = parser
            .reparse(&old, new_source)
            .expect("new source parses incrementally");

        assert!(!reparsed.changed_ranges.is_empty());
        assert!(
            reparsed
                .unit
                .tree()
                .root_node()
                .to_sexp()
                .contains("await_expression")
        );
    }

    #[test]
    fn no_op_reparse_reuses_the_existing_tree() {
        let source = "int value = 1;\n";
        let mut parser = SyntaxParser::new().expect("grammar loads");
        let old = parser
            .parse(PathBuf::from("value.cr"), source)
            .expect("source parses");
        let reparsed = parser
            .reparse(&old, source)
            .expect("no-op reparse succeeds");

        assert!(reparsed.changed_ranges.is_empty());
        assert_eq!(reparsed.unit.source(), source);
    }
}
